import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import {Inter} from "next/font/google"
import Provider from "./provider";
import { Toaster } from "@/components/ui/sonner"

const inter = Inter({
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${inter.className}`}
        >
          <div  className="container hidden">
            <div className="flex items-center justify-center h-screen">
              <h1 className="text-4xl">Laptop View only :)</h1>
            </div>
          </div>
          <div className="body-container">
            <Provider>
              {children}
            </Provider>
            <Toaster />

          </div>
        </body>

      </html>
    </ClerkProvider>
  );
}
